{% set name = "pep8-naming" %}
{% set version = "0.15.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: f6f4a499aba2deeda93c1f26ccc02f3da32b035c8b2db9696b730ef2c9639d29

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<39]

requirements:
  host:
    - pip
    - python
    - wheel
    - setuptools
  run:
    - python
    - flake8 >=5.0.0

test:
  source_files:
    - run_tests.py
    - testsuite
  imports:
    - pep8ext_naming
  commands:
    - pip check
    - python run_tests.py
  requires:
    - pip

about:
  home: https://github.com/PyCQA/pep8-naming
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Plug-in for flake 8 to check the PEP-8 naming conventions'
  description: This module provides a plugin for flake8, the Python code checker
  dev_url: https://github.com/PyCQA/pep8-naming
  doc_url: https://github.com/PyCQA/pep8-naming/blob/main/README.rst

extra:
  recipe-maintainers:
    - dopplershift
    - jakirkham
    - sigmavirus24
