{% set version = "0.4.1" %}

package:
  name: pep8-naming
  version: {{ version }}

source:
  fn: pep8-naming-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/pep8-naming/pep8-naming-{{ version }}.tar.gz
  sha256: 4eedfd4c4b05e48796f74f5d8628c068ff788b9c2b08471ad408007fc6450e5a

build:
  script: python setup.py install --single-version-externally-managed --record record.txt
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - flake8

test:
  commands:
    - "flake8 --version | grep naming:"

about:
  home: https://github.com/PyCQA/pep8-naming
  license: MIT License
  summary: 'Plug-in for flake 8 to check the PEP-8 naming conventions'

extra:
  recipe-maintainers:
    - dopplershift
    - sigmavirus24
