travis:
  secure:
    BINSTAR_TOKEN: yfI4akmdmNJli+c160W/RQ/lKSYfaoT5ZEsPbEUtWspuEYhU/6CBhgA7PalXPx7LJEBsvDa7bUscXdR0JeDaL8b1SURoTWZY5rhkDvSSkn7XSujueB1/dZrrrOzbn5Qnf8fZyJKqr+G8poCtjKAEx6AQhIHzee7LsCysoebZ0E6gqwIfd/PO3xHcoyVUh5iofeF4M/MqfLidxIdYf30+fKZJ1/o+72v5AHRcCxgInsE+EFyDlZIAU9gwwCKu0MhGz+pKLaWzq9V4nGkcynyTh4yiq1ZZB44Ki4tYhw2ylwbG4PxdbBIevxkFbr/uglrbtacYx8Kr5XrzrYCRf39I3OXv32quuaIvDEZCQdKL7p3x1PDLu6EsoDsnNgjdGgB/ToSqmnUVU/GatnINdzt5lDibL7aJ7Vh4YfbKIToGMgzV5eJLnwSygPLC0CNll7hmFysF9TXVjMZjZIKUT5d6E62Z/K3cAnu+HijQK6s0Y3tIpdAtQ2fyRWqBpLklqZPGhxUaAAXol6wOc1+DCMwuhT0oCkXqwt26BsyUkmF4acaQhIPAef4VpKv4Y7x8W2KNXG7+GYaKl8EjNg1A2o4wGQF1WnzD0xwg7xP7ZAy10H+RjPciSNEfWrjVD/PiDPmY3YiWB/8zs1LQ7rjR53yWg9YG2kFSGDVQa9qrfB5Neys=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
